[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
script = 'execute'
broadcast = 'records'
fs_permissions = [ {access = "read-write", path = "./"} ]
optimizer = true
optimizer_runs = 999999
solc_version = "0.8.15"

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
